package Administrador;

import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import modelo.Conexion;
import javax.swing.JOptionPane;
import Administrador.UsuarioBack;


public class ControlUsuario extends javax.swing.JFrame {

    private String nombreUsuario;
    private Connection conn = null;

    public ControlUsuario(String nombreUsuario) {
        initComponents();

        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("RUT");
        modelo.addColumn("NOMBRE");
        modelo.addColumn("APELLIDO");
        modelo.addColumn("NUMERO");
        modelo.addColumn("CORREO");
        modelo.addColumn("PASS");
        modelo.addColumn("TIPOUSER");
        tblCtrlUsuario.setModel(modelo);

        // Configuración del ComboBox TipoUsuario
        cbTipoUser.addItem("administrador");
        cbTipoUser.addItem("vendedor");
        cbTipoUser.addItem("reponedor");

        this.nombreUsuario = nombreUsuario;
        txtNomCtrlUsuario.setText(nombreUsuario);

        // Conexión a la base de datos
        conn = Conexion.conectar();
        if (conn == null) {
            JOptionPane.showMessageDialog(this, "No se pudo conectar a la base de datos");
        }
    }

    private void limpiarCampos() {
        txtRutCtrlUsuario.setText("");
        txtNombreCtrlUsuario.setText("");
        txtApellidoCtrlUsuario.setText("");
        txtNumeroCtrlUsuario.setText("");
        txtCorreoCtrlUsuario.setText("");
        txtPassCtrlUsuario.setText("");
        cbTipoUser.setSelectedIndex(0);

    }
    // Resto del código de la clase

    

    private void BtnBuscarCtrlUserActionPerformed(java.awt.event.ActionEvent evt) {
        String rut = txtBuscarCtrlUser.getText();
        buscarUsuario(rut);
    }

    public void windowStateChanged(WindowEvent e) {
        if (e.getNewState() == JFrame.MAXIMIZED_BOTH) {
            // Haz algo cuando la ventana se maximice
        } else if (e.getNewState() == JFrame.NORMAL) {
            // Haz algo cuando la ventana vuelva a su tamaño normal
        }
    }

    // Desconexión de la base de datos
    private void formWindowClosing(java.awt.event.WindowEvent evt) {
        Conexion.desconectar(conn);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackGround = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        UserLabelimg = new javax.swing.JLabel();
        txtNomCtrlUsuario = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        BtnBackAdminUser = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txtBuscarCtrlUser = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        BtnBuscarUser = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        txtNombreCtrlUsuario = new javax.swing.JTextField();
        txtApellidoCtrlUsuario = new javax.swing.JTextField();
        txtRutCtrlUsuario = new javax.swing.JTextField();
        txtNumeroCtrlUsuario = new javax.swing.JTextField();
        txtCorreoCtrlUsuario = new javax.swing.JTextField();
        tablaUsuarioCrtl = new javax.swing.JScrollPane();
        tblCtrlUsuario = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        BtnEditarUser = new javax.swing.JButton();
        BtnGuardarCtrlUser = new javax.swing.JButton();
        BtnLimpiarUser = new javax.swing.JButton();
        BtnEliminarUser = new javax.swing.JButton();
        BtnMostrarUserBD = new javax.swing.JButton();
        BtnExcelUser = new javax.swing.JButton();
        txtPassCtrlUsuario = new javax.swing.JPasswordField();
        cbTipoUser = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        BackGround.setBackground(new java.awt.Color(255, 255, 255));
        BackGround.setForeground(new java.awt.Color(255, 255, 255));
        BackGround.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/estatua.png"))); // NOI18N
        BackGround.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 760));

        jPanel1.setBackground(new java.awt.Color(51, 51, 251));
        jPanel1.setToolTipText("");

        UserLabelimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/user.png"))); // NOI18N

        txtNomCtrlUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomCtrlUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(UserLabelimg)
                .addGap(41, 41, 41)
                .addComponent(txtNomCtrlUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(UserLabelimg)
                    .addComponent(txtNomCtrlUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        BackGround.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, 390, 70));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logochico.png"))); // NOI18N
        BackGround.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 10, 210, 80));

        BtnBackAdminUser.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        BtnBackAdminUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/cerrar.png"))); // NOI18N
        BtnBackAdminUser.setText("ADMIN");
        BtnBackAdminUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBackAdminUserActionPerformed(evt);
            }
        });
        BackGround.add(BtnBackAdminUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 650, 270, 50));

        jPanel2.setBackground(new java.awt.Color(51, 51, 251));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("BUSCAR  USUARIO");

        BtnBuscarUser.setText("buscar");
        BtnBuscarUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBuscarUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtBuscarCtrlUser)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE))
                .addGap(43, 43, 43)
                .addComponent(BtnBuscarUser, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscarCtrlUser, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnBuscarUser, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );

        BackGround.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, 360, 100));

        jPanel3.setBackground(new java.awt.Color(51, 51, 251));

        jTextField3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTextField3.setText("NOMBRE");

        jTextField4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTextField4.setText("RUT");

        jTextField5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTextField5.setText("APELLIDO");

        jTextField6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTextField6.setText("CORREO");

        jTextField7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTextField7.setText("NUMERO");
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });

        jTextField8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTextField8.setText("PASS");
        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });

        jTextField9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTextField9.setText("TIPO USUARIO");

        tblCtrlUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "RUT", "NOMBRE", "APELLIDO", "NUMERO", "CORREO", "PASS", "TIPO USUARIO"
            }
        ));
        tblCtrlUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCtrlUsuarioMouseClicked(evt);
            }
        });
        tablaUsuarioCrtl.setViewportView(tblCtrlUsuario);

        BtnEditarUser.setBackground(new java.awt.Color(255, 255, 255));
        BtnEditarUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/BTN-ACTUALIZAR.png"))); // NOI18N
        BtnEditarUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEditarUserActionPerformed(evt);
            }
        });

        BtnGuardarCtrlUser.setBackground(new java.awt.Color(255, 255, 255));
        BtnGuardarCtrlUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ICONGUARDAR.png"))); // NOI18N
        BtnGuardarCtrlUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGuardarCtrlUserActionPerformed(evt);
            }
        });

        BtnLimpiarUser.setBackground(new java.awt.Color(255, 255, 255));
        BtnLimpiarUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/limpiar (1).png"))); // NOI18N
        BtnLimpiarUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLimpiarUserActionPerformed(evt);
            }
        });

        BtnEliminarUser.setBackground(new java.awt.Color(255, 255, 255));
        BtnEliminarUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/eliminar.png"))); // NOI18N
        BtnEliminarUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnEliminarUserMouseClicked(evt);
            }
        });
        BtnEliminarUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEliminarUserActionPerformed(evt);
            }
        });

        BtnMostrarUserBD.setText("mostrar todos");
        BtnMostrarUserBD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMostrarUserBDActionPerformed(evt);
            }
        });

        BtnExcelUser.setText("excel");
        BtnExcelUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnExcelUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BtnGuardarCtrlUser, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(BtnEditarUser, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(BtnEliminarUser)
                .addGap(26, 26, 26)
                .addComponent(BtnLimpiarUser, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(BtnMostrarUserBD, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(BtnExcelUser)
                .addContainerGap(77, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnGuardarCtrlUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnEditarUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnLimpiarUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnEliminarUser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnMostrarUserBD)
                    .addComponent(BtnExcelUser))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtPassCtrlUsuario.setText("jPasswordField1");

        cbTipoUser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "" }));
        cbTipoUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipoUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tablaUsuarioCrtl, javax.swing.GroupLayout.PREFERRED_SIZE, 1048, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRutCtrlUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombreCtrlUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtApellidoCtrlUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNumeroCtrlUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCorreoCtrlUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPassCtrlUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField9)
                            .addComponent(cbTipoUser, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRutCtrlUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombreCtrlUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApellidoCtrlUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumeroCtrlUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCorreoCtrlUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPassCtrlUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbTipoUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(tablaUsuarioCrtl, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );

        BackGround.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, 1100, 410));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackGround, javax.swing.GroupLayout.DEFAULT_SIZE, 1551, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackGround, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomCtrlUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomCtrlUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomCtrlUsuarioActionPerformed

    private void BtnBackAdminUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBackAdminUserActionPerformed
        Admin ventanaAdmin = new Admin();
        ventanaAdmin.setVisible(true);
        this.dispose(); // Cierra la ventana actual
    }//GEN-LAST:event_BtnBackAdminUserActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void BtnBuscarUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscarUserActionPerformed
        String rut = txtBuscarCtrlUser.getText();
        buscarUsuario(rut);
    }

    private void buscarUsuario(String rut) {
        // Limpiar tabla
        DefaultTableModel modelo = (DefaultTableModel) tblCtrlUsuario.getModel();
        modelo.setRowCount(0);

        // Realizar consulta a la base de datos
        String sql = "SELECT * FROM usuario WHERE rut = ?";
        try {
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setString(1, rut);
            ResultSet rs = ps.executeQuery();

            while (rs.next()) {
                Object[] fila = new Object[7];
                fila[0] = rs.getString("RUT");
                fila[1] = rs.getString("NOMBRE");
                fila[2] = rs.getString("APELLIDO");
                fila[3] = rs.getString("NUMERO");
                fila[4] = rs.getString("CORREO");
                fila[5] = rs.getString("PASS");
                fila[6] = rs.getString("TIPOUSER");
                modelo.addRow(fila);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al buscar usuario: " + e.getMessage());
        }

    }//GEN-LAST:event_BtnBuscarUserActionPerformed

    private void BtnGuardarCtrlUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGuardarCtrlUserActionPerformed
        String rut = txtRutCtrlUsuario.getText();
        String nombre = txtNombreCtrlUsuario.getText();
        String apellido = txtApellidoCtrlUsuario.getText();
        String numero = txtNumeroCtrlUsuario.getText();
        String correo = txtCorreoCtrlUsuario.getText();
        String pass = txtPassCtrlUsuario.getText();
        String tipoUsuario = "";
        if (cbTipoUser.getSelectedItem() != null) {
            tipoUsuario = cbTipoUser.getSelectedItem().toString();
        }

        // Verificar que los campos obligatorios estén completos
        if (rut.equals("") || nombre.equals("") || apellido.equals("") || correo.equals("") || pass.equals("")) {
            JOptionPane.showMessageDialog(this, "Por favor complete todos los campos obligatorios.");
            return;
        }

        // Crear un objeto de usuario con los valores obtenidos
        Usuario usuario = new Usuario(rut, nombre, apellido, numero, correo, pass, tipoUsuario);

        // Guardar el usuario en la base de datos
        UsuarioBack usuarioBack = new UsuarioBack();
        boolean resultado = usuarioBack.guardarUsuario(usuario);

        // Verificar si el usuario fue guardado correctamente
        if (resultado) {
            JOptionPane.showMessageDialog(this, "Usuario guardado correctamente.");
            limpiarCampos();
        } else {
            JOptionPane.showMessageDialog(this, "Ocurrió un error al guardar el usuario.");
        }
    }//GEN-LAST:event_BtnGuardarCtrlUserActionPerformed

    private void BtnMostrarUserBDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMostrarUserBDActionPerformed
        // Obtener la lista de usuarios desde la base de datos
    UsuarioBack usuarioBack = new UsuarioBack();
        var listaUsuarios = usuarioBack.obtenerTodosLosUsuarios();

    // Crear el modelo de la tabla con las columnas necesarias
    DefaultTableModel modeloTabla = new DefaultTableModel();
    modeloTabla.addColumn("Rut");
    modeloTabla.addColumn("Nombre");
    modeloTabla.addColumn("Apellido");
    modeloTabla.addColumn("Número");
    modeloTabla.addColumn("Correo");
    modeloTabla.addColumn("Pass");
    modeloTabla.addColumn("Tipo de Usuario");

    // Agregar las filas a la tabla con los datos de los usuarios
    for (Usuario usuario : listaUsuarios) {
        Object[] fila = new Object[7];
        fila[0] = usuario.getRut();
        fila[1] = usuario.getNombre();
        fila[2] = usuario.getApellido();
        fila[3] = usuario.getNumero();
        fila[4] = usuario.getCorreo();
        fila[5] = usuario.getPass();
        fila[6] = usuario.getTipouser();
        modeloTabla.addRow(fila);
    }

    // Asignar el modelo a la tabla
    tblCtrlUsuario.setModel(modeloTabla);


    
    }//GEN-LAST:event_BtnMostrarUserBDActionPerformed


    private void BtnEliminarUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEliminarUserActionPerformed
       
    }//GEN-LAST:event_BtnEliminarUserActionPerformed

    private void BtnEliminarUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnEliminarUserMouseClicked
        int selectedRow = tblCtrlUsuario.getSelectedRow();
    String rut = txtRutCtrlUsuario.getText();
    if (selectedRow == -1 && rut.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Debe seleccionar un usuario o ingresar un RUT válido.");
        return;
    }
    int response = JOptionPane.showConfirmDialog(this, "¿Está seguro de que desea eliminar este usuario?", "Confirmación", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
    if (response == JOptionPane.YES_OPTION) {
        if (selectedRow != -1) {
            DefaultTableModel model = (DefaultTableModel) tblCtrlUsuario.getModel();
            String rutToDelete = (String) model.getValueAt(selectedRow, 0);
            eliminarUsuarioPorRut(rutToDelete);
        } else {
            eliminarUsuarioPorRut(rut);
        }
        cargarUsuarios();
        limpiarCampos();
    }
    }//GEN-LAST:event_BtnEliminarUserMouseClicked

    private void tblCtrlUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCtrlUsuarioMouseClicked
        int filaSeleccionada = tblCtrlUsuario.getSelectedRow();
    if (filaSeleccionada >= 0) {
        String rut = tblCtrlUsuario.getValueAt(filaSeleccionada, 0).toString();
        String nombre = tblCtrlUsuario.getValueAt(filaSeleccionada, 1).toString();
        String apellido = tblCtrlUsuario.getValueAt(filaSeleccionada, 2).toString();
        String numero = tblCtrlUsuario.getValueAt(filaSeleccionada, 3).toString();
        String correo = tblCtrlUsuario.getValueAt(filaSeleccionada, 4).toString();
        String pass = tblCtrlUsuario.getValueAt(filaSeleccionada, 5).toString();
        String tipoUser = tblCtrlUsuario.getValueAt(filaSeleccionada, 6).toString();
        
        txtRutCtrlUsuario.setText(rut);
        txtNombreCtrlUsuario.setText(nombre);
        txtApellidoCtrlUsuario.setText(apellido);
        txtNumeroCtrlUsuario.setText(numero);
        txtCorreoCtrlUsuario.setText(correo);
        txtPassCtrlUsuario.setText(pass);
        cbTipoUser.setSelectedItem(tipoUser);
    }
    }//GEN-LAST:event_tblCtrlUsuarioMouseClicked

    private void BtnLimpiarUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLimpiarUserActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_BtnLimpiarUserActionPerformed

    private void BtnEditarUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEditarUserActionPerformed
        String rut = txtRutCtrlUsuario.getText();
    String nombre = txtNombreCtrlUsuario.getText();
    String apellido = txtApellidoCtrlUsuario.getText();
    String numero = txtNumeroCtrlUsuario.getText();
    String correo = txtCorreoCtrlUsuario.getText();
    String pass = txtPassCtrlUsuario.getText();
    String tipouser = cbTipoUser.getSelectedItem().toString();
    
    Usuario usuario = new Usuario(rut, nombre, apellido, numero, correo, pass, tipouser);
    UsuarioBack usuarioBack = new UsuarioBack();
    
    if (usuarioBack.actualizarUsuario(usuario)) {
        JOptionPane.showMessageDialog(null, "El usuario se actualizó correctamente");
    } else {
        JOptionPane.showMessageDialog(null, "No se pudo actualizar el usuario");
    }
    }//GEN-LAST:event_BtnEditarUserActionPerformed

    private void cbTipoUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTipoUserActionPerformed

    private void BtnExcelUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnExcelUserActionPerformed
       try {
        JFileChooser seleccionarArchivo = new JFileChooser();
        seleccionarArchivo.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);

        if (seleccionarArchivo.showSaveDialog(null) == JFileChooser.APPROVE_OPTION) {
            String rutaArchivo = seleccionarArchivo.getSelectedFile().getAbsolutePath() + "\\UsuariosRegistrados.xlsx";
            UsuarioBack usuarioback = new UsuarioBack();
            List<Usuario> listaUsuarios = usuarioback.obtenerTodosLosUsuarios();
            usuarioback.generarExcelDeUsuarios(listaUsuarios, rutaArchivo);
            JOptionPane.showMessageDialog(null, "El archivo se ha creado correctamente", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Ocurrió un error al generar el archivo Excel: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_BtnExcelUserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ControlUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ControlUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ControlUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ControlUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BackGround;
    private javax.swing.JButton BtnBackAdminUser;
    private javax.swing.JButton BtnBuscarUser;
    private javax.swing.JButton BtnEditarUser;
    private javax.swing.JButton BtnEliminarUser;
    private javax.swing.JButton BtnExcelUser;
    private javax.swing.JButton BtnGuardarCtrlUser;
    private javax.swing.JButton BtnLimpiarUser;
    private javax.swing.JButton BtnMostrarUserBD;
    private javax.swing.JLabel UserLabelimg;
    private javax.swing.JComboBox<String> cbTipoUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JScrollPane tablaUsuarioCrtl;
    private javax.swing.JTable tblCtrlUsuario;
    private javax.swing.JTextField txtApellidoCtrlUsuario;
    private javax.swing.JTextField txtBuscarCtrlUser;
    private javax.swing.JTextField txtCorreoCtrlUsuario;
    private javax.swing.JTextField txtNomCtrlUsuario;
    private javax.swing.JTextField txtNombreCtrlUsuario;
    private javax.swing.JTextField txtNumeroCtrlUsuario;
    private javax.swing.JPasswordField txtPassCtrlUsuario;
    private javax.swing.JTextField txtRutCtrlUsuario;
    // End of variables declaration//GEN-END:variables

    private void cargarUsuarios() {
    DefaultTableModel modelo = (DefaultTableModel) tblCtrlUsuario.getModel();
    modelo.setRowCount(0);
    try {
        String sql = "SELECT * FROM usuario";
        PreparedStatement pstmt = conn.prepareStatement(sql);
        ResultSet rs = pstmt.executeQuery();
        while (rs.next()) {
            String rut = rs.getString("rut");
            String nombre = rs.getString("nombre");
            String apellido = rs.getString("apellido");
            String numero = rs.getString("numero");
            String correo = rs.getString("correo");
            String pass = rs.getString("pass");
            String tipoUser = rs.getString("tipoUser");

            modelo.addRow(new Object[]{rut, nombre, apellido, numero, correo, pass, tipoUser});
        }
        rs.close();
        pstmt.close();
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Error al cargar los usuarios: " + ex.getMessage());
    }
}

private void eliminarUsuariosPorRut(String rut) {
    
}

    private void eliminarUsuarioPorRut(String rutToDelete) {
        
        try {
        String sql = "DELETE FROM usuario WHERE rut = ?";
            try (PreparedStatement pstmt = conn.prepareStatement(sql)) {
                pstmt.setString(1, rutToDelete);
                pstmt.executeUpdate();
            }
        JOptionPane.showMessageDialog(this, "Usuario eliminado correctamente.");
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Error al eliminar el usuario: " + ex.getMessage());
    }
    }

    private void generarExcelDeUsuarios(List<Usuario> listaUsuarios, String rutaArchivo) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
    


    

    

}
